//https://www.youtube.com/watch?v=zWJtOIopJvk
package aplicacionFCT.gui;

import aplicacionFCT.dto.Alumno;
import aplicacionFCT.dto.Usuario;
import java.awt.Image;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
import logica.LogicaNegocio;

/**
 *
 * @author AntonioLópezMielgo
 */
public class pantallaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form pantallaPrincipal
     */
    public pantallaPrincipal() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/aplicacionFCT/gui/imgs/logo.png")).getImage());
       //OBLIGAMOS AL USUARIO A INICIAR SESION
        jButtonAlumno.setEnabled(false);
        jButtonEmpresa.setEnabled(false);
   
    }
   public void establecerUsuario(Usuario usuario) {
      
        jButtonAlumno.setEnabled(true);

        jButtonEmpresa.setEnabled(true);

        jMenuInicioSesion.setText("Cerrar sesión");
         jMenuInicioSesion.setText(usuario.getNombre());

    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenu1 = new javax.swing.JMenu();
        jPanelAlumno = new javax.swing.JPanel();
        jButtonAlumno = new javax.swing.JButton();
        jButtonEmpresa = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuInicioSesion = new javax.swing.JMenu();
        jCheckBoxMenuItemInicioSesion = new javax.swing.JCheckBoxMenuItem();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout();
        flowLayout1.setAlignOnBaseline(true);
        jPanelAlumno.setLayout(flowLayout1);

        jButtonAlumno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionFCT/gui/imgs/estudieante.jpg"))); // NOI18N
        jButtonAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlumnoActionPerformed(evt);
            }
        });
        jPanelAlumno.add(jButtonAlumno);

        jButtonEmpresa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/aplicacionFCT/gui/imgs/empresa.png"))); // NOI18N
        jButtonEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmpresaActionPerformed(evt);
            }
        });
        jPanelAlumno.add(jButtonEmpresa);

        jMenuInicioSesion.setText("Iniciar Sesion");

        jCheckBoxMenuItemInicioSesion.setSelected(true);
        jCheckBoxMenuItemInicioSesion.setText("Iniciar Sesion");
        jCheckBoxMenuItemInicioSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemInicioSesionActionPerformed(evt);
            }
        });
        jMenuInicioSesion.add(jCheckBoxMenuItemInicioSesion);

        jMenuBar1.add(jMenuInicioSesion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addComponent(jPanelAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
  //
    private void jCheckBoxMenuItemInicioSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemInicioSesionActionPerformed
        // TODO add your handling code here:
        iniciarSesion inciciosesion=new iniciarSesion(this, true);
        inciciosesion.setVisible(true);
        
        
    }//GEN-LAST:event_jCheckBoxMenuItemInicioSesionActionPerformed

    private void jButtonAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlumnoActionPerformed
        DatosAlumnos datosAlumnos=new DatosAlumnos(this,true);
        datosAlumnos.setVisible(true);
    }//GEN-LAST:event_jButtonAlumnoActionPerformed

    private void jButtonEmpresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmpresaActionPerformed
       DatosEmpresas datosEmpresa= new DatosEmpresas(this,true);
       datosEmpresa.setVisible(true);
    }//GEN-LAST:event_jButtonEmpresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlumno;
    private javax.swing.JButton jButtonEmpresa;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemInicioSesion;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuInicioSesion;
    private javax.swing.JPanel jPanelAlumno;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void getImagen() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
